[project]
name = "aids"
version = "0.1.0"
description = "El analizador inteligente de datos simples."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "pandas-stubs>=2.3.2.250926",
]
